image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/cdtn-veille-git

labels:
  app.kubernetes.io/part-of: cdtn-veille-git
  owner: cdtn-veille-git
  team: cdtn-veille-git

deployment:
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

  port: 3000

  livenessProbe:
    periodSeconds: 20
    port: 3000
  readinessProbe:
    periodSeconds: 20
    port: 3000

  resources:
    limits:
      memory: 2048Mi
      cpu: 1000m
    requests:
      memory: 1024Mi
      cpu: 100m

  env:
    - name: NODE_ENV
      value: "production"

service:
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: "cdtn-veille-git.fabrique.social.gouv.fr"
      paths:
        - path: /
          servicePort: 3000
  tls:
    - hosts:
        - "cdtn-veille-git.fabrique.social.gouv.fr"
      secretName: cdtn-veille-git-crt
