include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v8.0.0

variables:
  PROJECT: "veille-git"
  #RANCHER_PROJECT_ID: "c-gsm8d:p-pwpk6" # "default" project id here
  PORT: 3000
  VALUES_FILE: ./.k8s/app.values.yml # Your values
  DOCKER_BUILD_ARGS: "--no-cache"
