include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v8.0.0

variables:
  PROJECT: "cdtn-veille-git"
  K8S_NAMESPACE: "cdtn-veille-git"
  RANCHER_PROJECT_ID: "c-kk8xm:p-8n8mv" # "default" project id here
  PORT: 3000
  VALUES_FILE: ./.k8s/app.values.yml # Your values
  DOCKER_BUILD_ARGS: "--no-cache"
