include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v15.0.1

variables:
  PROJECT: "cdtn-veille-git"
  RANCHER_PROJECT_ID: "c-l9h59:p-6b2d4" # "default" project id here
  PORT: 3000
  VALUES_FILE: ./.k8s/app.values.yml # Your values
  DOCKER_BUILD_ARGS: "--no-cache"
